### ISSUE TITLE
request: 2022 Roadmap

### ISSUE THREAD

**Issue by i0bs** [i0bs/retux#9]
### What's the feature?

Hello, everyone!

As part of retux's main plan to get everything of the Discord API implemented with our four big philosophies, when an item is checked off of our 2022 roadmap list, it means that "this has been completed, and has all 4 philosophies considered." With that in mind, here is an non-exhaustive list of things that are still remaining before the pending release of version 1.0.

- [ ] Client
  - [ ] Mixins
    - [ ] Implement `Respondable` mixin.
      - [ ] Add `respond()` main method.
      - [ ] Add `edit()` method, including the origin if needed.
      - [ ] Add `delete()` main method.
    - [ ] Implement `Mentionable` mixin. (This checks for if an object can be mentioned and meant to be put on top of any object with an ID.)
    - [ ] Implement `Event` mixin.
      - [ ] Have the mixin be further subclassable for events with the resource.
      - [ ] Mixin must contain the original event name and an instance of the bot.
  - [ ] Resources
    - [ ] Implement `Snowflake` object
    - [ ] Implement `Image` object
    - [ ] Implement `Component` object
    - [ ] Implement `Object` object (in reference to Discord resources)
    - [ ] Implement `Partial` object (used to refer to "partial")
    - [ ] Implement `Application` object
      - [ ] Add partial `PartialApplication` object
    - [ ] Implement `AuditLog` object
    - [ ] Implement `AutoModeration` object
    - [ ] Implement `Channel` object
      - [ ] Add partial `TextChannel` object
      - [ ] Add partial `AnnouncementChannel` object
      - [ ] Add partial `ForumChannel` object
      - [ ] Add partial `DMChannel` object
      - [ ] Add partial `StageChannel` object
      - [ ] Add partial `VoiceChannel` object
      - [ ] Add partial `ThreadChannel` object 
    - [ ] Implement `Emoji` object
      - [ ] Add partial `PartialEmoji` object
    - [ ] Implement `Guild` object
      - [ ] Add partial `UnavailableGuild` object
      - [ ] Add partial `PartialGuild` object
    - [ ] Implement `GuildScheduledEvent` object
    - [ ] Implement `GuildTemplate` object
    - [ ] Implement `Invite` object
    - [ ] Implement `StageInstance` object
    - [ ] Add alias `Stage` object
    - [ ] Implement `Sticker` object
    - [ ] Implement `User` object
    - [ ] Implement `Voice` object
    - [ ] Implement `Webhook` object
  - [ ] Implement `Intents` object.
  - [ ] Implement error handlers.
    - [ ] Add `@error` decorator.
    - [ ] Add `@command.error` decorator.
    - [ ] Add `on_error(command)` asynchronous context manager
  - [ ] Implement Gateway handlers.
    - [ ] Add `@on` decorator.
      - [ ] Allow application to functions and methods.
      - [ ] Allow application to classes.
      - [ ] Allow the ability to read for specific attributes and values provided.
      - [ ] Allow for `@on.autocomplete` events.
      - [ ] Allow for `@on.error` exceptions.
      - [ ] Allow for `@on.component` events.
    - [ ] Add `@command` decorator.
      - [ ] Add alias `@user_command` decorator.
      - [ ] Add alias `@message_command` decorator.
      - [ ] Add alias `@channel_command` decorator. (Pending release from Discord)
      - [ ] Add `@command.autocomplete` decorator.
      - [ ] Add `@command.on("option_name")` decorator. (Only triggered when a specific option is provided)
        - [ ] Allow chaining for `@command.on("opt_1").on("opt_2")`
        - [ ] Allow numerous inputs for `@command.on(["opt_1", "opt_2"])` for lists of options.
    - [ ] Add `@component` decorator.
    - [ ] Add `@cooldown` decorator.
    - [ ] Add alias `@option` decorator.
    - [ ] Add alias `@permission` decorator.
    - [ ] Add alias `@subcommand` decorator.
      - [ ] Allow assumption for the decorator by itself being the "base."
      - [ ] Allow for `@subcommand.group` group types.
      - [ ] Allow for `@group.command` command in group.
    - [ ] Implement `Extension` object.
      - [ ] Implement hot reloading.
        - [ ] Set up asynchronous `trio.Nursery` to control and manage hot reloads.
      - [ ] Design to be used as anonymous classes.
      - [ ] Allow for loading directly via. bot instance as `*(name, ...))`
- [ ] Utilities
  - [ ] Implement `get()` feature.
    - [ ] Add `cache` and `http` strategies.
    - [ ] Allow and add `fetch`/`search`-like functionalities.
  - [ ] Implement `utils.utils` module for attrs-based utilities, i.e. factories and validators.
- [ ] API
  - [ ] Events
    - [ ] Implement `_Event` object. (To designate what is now an event)
    - [ ] Implement event lookup tables as objects. (Must be fully completed!)
    - [ ] Implement `Ready` object.
    - [ ] Implement `Resumed` object.
    - [ ] Implement `Reconnect` object.
    - [ ] Implement `InvalidSession` object.
  - [ ] Implement error exceptions.
    - [ ] Add `Permissions` exception.
    - [ ] Add `ExceededCharLimit` exception.
    - [ ] Add `NotDeleteable` exception.
    - [ ] Add `MissingAccess` exception.
    - [ ] Add `NotExistent` exception.
    - [ ] Add `MissingArg` exception.
    - [ ] Add `Ratelimited` exception.
  - [ ] Design the Gateway.
    - [ ] Add rate limitation logic.
    - [ ] Create infrastructure. (Metadata, payloads, protocol, ...)
    - [ ] Design asynchronous IO-friendly and complacent system.
    - [ ] Allow easy access to user-end specific properties.
    - [ ] Create connection, reconnection and heartbeater.
    - [ ] Allow the ability to change presence.
    - [ ] Allow the ability to request guild members.
    - [ ] Allow the ability to update the voice state.
  - [ ] Design the REST client.
    - [ ] Add API-complacent rate limitation logic.
    - [ ] Create infrastructure. (Rate limit, buckets, protocol ...)
    - [ ] Design asynchronously IO-friendly and complacent system.

### How does it work?

These are mainly the rules I have to people wanting to contribute or understand how the library is being developed. With our four main philosophies in mind, we also check for these as part of the basic structure for strictness.

- All objects that involve the use of `attrs` must:
  - Properly use the `utils.converters` functions supplied when dealing with a conversion.
  - Reiterate the name of the object in every docstring. (Look at `channel.py` and `message.py` for inspiration. 😃)
  - Leave a `TODO` comment for any fields with an object that does not exist yet.
  - Leave a `FIXME` if something is intentionally being done wrong, attached with why.
- A Gateway event must be structured with the `_Event` class.
- Resources (or dataclasses from gateway events; interactable...) must:
  - Use the `Object` to subclass from if the object in question as an `id` field by nature.
  - Use the `Partial` to subclass from if the object does not have `id` or is a partial of an existing object.
  - Follow the standards given for `attrs`.
- Infrastructures for any given client or design must:
  - Ensure a class is privatised by dundering. (Using an underscore at the beginning)
  - Have a protocol that only exposes public methods and attributes.
- Events for any Gateway event supplied must:
  - Have their edgecase defined in its respective lookup table.
  - Implement the ability to get `before` and `after` arguments if no event type was given.
  - Implement the ability to pass back a bot instance only if there is an `id` field in the resource.
  - (If for an event relating to removing) Check the TTL-timed cache, and if so give back as `before`. `after` must be what's currently given. `after` can be `MISSING` if deleted and `UnavailableGuild` if caused by a server outage or Trust and Safety.
  - Follow the standards given for `attrs`.

### Code of Conduct

- [X] I agree.

**Comment by i0bs** [comment]
Please note that this roadmap does not accurately reflect all items remaining for version 1.0. This is simply a planned list of things to work on, other tasks or requests may be created outside of this scope.
